version: '3'
services:
    database:
        image: mysql:8
        container_name: my_database
        restart: unless-stopped
        ports:
            - 33061:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_ROOT_HOST=%
        volumes:
            - ./bin/mysql:/var/lib/mysql
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        ports:
            - 33063:30000
        restart: unless-stopped
        depends_on:
            - database
        environment:
            - DATABASE_HOST=my_database
            - DATABASE_PORT=3306
            - DATABASE_USERNAME=root
            - DATABASE_PASSWORD=password
    frontend:
        build:
            context: ./antrianGigi
            dockerfile: ./Dockerfile
        ports:
            - "3000:80"
        restart: unless-stopped

